-- جدول البانرات للتطبيق (Banners Table)
create table banners (
  id bigint generated by default as identity primary key,
  image_url text not null,
  order_index int not null default 0,
  title text,
  description text,
  action_url text,
  is_active boolean not null default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- التعليق على الجدول
comment on table banners is 'جدول لتخزين بيانات البانرات التي تظهر في الصفحة الرئيسية';
comment on column banners.id is 'المعرف الفريد للبانر';
comment on column banners.image_url is 'رابط الصورة الخاصة بالبانر';
comment on column banners.order_index is 'ترتيب ظهور البانر';
comment on column banners.title is 'عنوان البانر (اختياري)';
comment on column banners.description is 'وصف البانر (اختياري)';
comment on column banners.action_url is 'رابط الإجراء عند النقر على البانر (اختياري)';
comment on column banners.is_active is 'حالة نشاط البانر (نشط أو غير نشط)';
comment on column banners.created_at is 'تاريخ إنشاء البانر';
comment on column banners.updated_at is 'تاريخ آخر تحديث للبانر';

-- إنشاء محفز (trigger) لتحديث تاريخ التعديل تلقائياً
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_banners_updated_at
before update on banners
for each row
execute function update_updated_at_column();

-- إضافة بيانات نموذجية (أمثلة لبانرات)
insert into banners (image_url, order_index, title, description, is_active) values
('https://example.com/banners/banner1.jpg', 1, 'خصم 60% على حقائب السفر', 'اشترِ الآن واحصل على خصم حصري على جميع حقائب السفر', true),
('https://example.com/banners/banner2.jpg', 2, 'سكن طلابي متميز', 'أفضل خيارات السكن الطلابي بأسعار مناسبة', true),
('https://example.com/banners/banner3.jpg', 3, 'شقق عائلية', 'شقق واسعة ومريحة للعائلات بمواقع متميزة', true),
('https://example.com/banners/banner4.jpg', 4, 'استوديوهات مفروشة', 'تصميم عصري وأثاث متميز يناسب احتياجاتك', true);

-- إنشاء سياسات الأمان
-- سياسة القراءة (يمكن لأي مستخدم قراءة البانرات)
create policy "البانرات مرئية للجميع"
on banners for select
to anon
using (true);

-- سياسة الإدخال والتعديل والحذف (للمشرفين فقط)
-- ملاحظة: يجب تعديل هذه السياسات لتناسب نظام المصادقة الخاص بك
create policy "يمكن للمشرفين إدارة البانرات"
on banners for all
to authenticated
using (
  -- يمكنك تعديل هذا الشرط حسب نظام الصلاحيات لديك
  (auth.uid() in (select id from admins))
); 