-- SQL script for creating app_updates table in Supabase

-- Create app_updates table
CREATE TABLE IF NOT EXISTS public.app_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    download_url TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    primary_color VARCHAR(10),
    secondary_color VARCHAR(10),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE
);

-- Add comment to the table
COMMENT ON TABLE public.app_updates IS 'Stores app update information including version and download URL';

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_app_updates_is_active ON public.app_updates(is_active);
CREATE INDEX IF NOT EXISTS idx_app_updates_created_at ON public.app_updates(created_at);

-- Set RLS (Row Level Security)
ALTER TABLE public.app_updates ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Allow anyone to read active updates
CREATE POLICY "Allow anyone to read active updates" 
    ON public.app_updates FOR SELECT 
    USING (is_active = TRUE);

-- Allow only authenticated users with admin role to modify the table
CREATE POLICY "Allow admins to manage updates" 
    ON public.app_updates FOR ALL 
    USING (auth.uid() IN (
        SELECT user_id FROM public.profiles WHERE role = 'admin'
    ));

-- Insert sample data (optional)
/*
INSERT INTO public.app_updates (version, description, download_url, is_active, primary_color, secondary_color)
VALUES 
    ('1.1.0', 'تحديث جديد متاح! يتضمن تحسينات في الأداء وميزات جديدة', 'https://example.com/download/app-v1.1.0.apk', TRUE, '1E88E5', '1565C0');
*/

-- IMPORTANT: Run this SQL script in the Supabase SQL editor 